import { api, apiError, json } from './api';
import { clearSession, requireSession } from './auth';

type AnyRecord = Record<string, any>;
const root = document.querySelector('#dashboard-root') as HTMLElement;
const toast = document.querySelector('#toast') as HTMLElement;
const modalBackdrop = document.querySelector('#modal-backdrop') as HTMLElement;
const modal = document.querySelector('#modal') as HTMLElement;
let licenses: AnyRecord[] = [];
let mappings: AnyRecord[] = [];
let accounts: AnyRecord[] = [];
let logs: AnyRecord[] = [];

const esc = (value: unknown) => String(value ?? '—').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[char] || char);
const date = (value: unknown) => value ? new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium' }).format(new Date(String(value).replace(' ', 'T'))) : '—';
const dateInput = (value: unknown) => { if (!value) return ''; const parsed = new Date(String(value).replace(' ', 'T')); return Number.isFinite(parsed.getTime()) ? parsed.toISOString().slice(0, 10) : ''; };
const isActive = (item: AnyRecord) => item.status === 'active' && (!item.current_period_end || new Date(String(item.current_period_end).replace(' ', 'T')).getTime() > Date.now());
const statusBadge = (status: string, label = status) => `<span class="badge ${esc(status)}">${esc(label)}</span>`;
const showToast = (text: string) => { toast.textContent = text; toast.classList.add('show'); window.setTimeout(() => toast.classList.remove('show'), 3200); };
const showError = (error: unknown) => showToast(apiError(error));
const setPage = (title: string, subtitle: string) => { document.querySelector('#page-title')!.textContent = title; document.querySelector('#page-subtitle')!.textContent = subtitle; };
const loading = () => { root.innerHTML = '<div class="panel"><div class="loading"><span class="spinner"></span>Loading data...</div></div>'; };
const empty = (icon: string, text: string) => `<div class="empty-state"><iconify-icon icon="${icon}"></iconify-icon><p>${text}</p></div>`;

function openModal(content: string) { modal.innerHTML = content; modalBackdrop.classList.add('open'); modal.querySelector('[data-modal-close]')?.addEventListener('click', closeModal); }
function closeModal() { modalBackdrop.classList.remove('open'); modal.innerHTML = ''; }
modalBackdrop.addEventListener('click', (event) => { if (event.target === modalBackdrop) closeModal(); });

function licenseTable(items: AnyRecord[], withActions = true) {
  if (!items.length) return empty('lucide:inbox', 'Belum ada license yang ditemukan.');
  return `<div class="table-wrap"><table><thead><tr><th>License</th><th>Customer</th><th>Plan</th><th>Status</th><th>Devices</th><th>Expires</th>${withActions ? '<th>Actions</th>' : ''}</tr></thead><tbody>${items.map((item) => `<tr><td><strong class="mono">${esc(item.key)}</strong><button class="copy-button" data-copy="${esc(item.key)}" title="Copy license key"><iconify-icon icon="lucide:copy" width="14"></iconify-icon></button></td><td><strong>${esc(item.email)}</strong></td><td>${esc(item.plan_type)}</td><td>${statusBadge(item.status, isActive(item) ? 'active' : item.status === 'revoked' ? 'revoked' : 'expired')}</td><td>${esc(item.devices_used ?? 0)} / ${esc(item.max_devices)}</td><td>${date(item.current_period_end)}</td>${withActions ? `<td><div class="row-actions"><button class="row-action" data-edit-license="${item.id}" title="Edit license"><iconify-icon icon="lucide:pencil" width="15"></iconify-icon></button><button class="row-action" data-activations="${item.id}" title="Manage devices"><iconify-icon icon="lucide:cpu" width="15"></iconify-icon></button>${item.status === 'revoked' ? `<button class="row-action" data-reactivate="${item.id}" title="Reactivate"><iconify-icon icon="lucide:rotate-ccw" width="15"></iconify-icon></button>` : `<button class="row-action" data-revoke="${item.id}" title="Revoke"><iconify-icon icon="lucide:ban" width="15"></iconify-icon></button>`}</div></td>` : ''}</tr>`).join('')}</tbody></table></div>`;
}

function bindCopy() { document.querySelectorAll<HTMLElement>('[data-copy]').forEach((button) => button.addEventListener('click', async () => { await navigator.clipboard.writeText(button.dataset.copy || ''); showToast('License key copied.'); })); }

async function loadLicenses() { const data = await api<{ licenses: AnyRecord[] }>('/admin/licenses'); licenses = data.licenses || []; return licenses; }

async function renderOverview() {
  setPage('Overview', 'Monitor your license ecosystem.'); loading();
  try {
    const items = await loadLicenses();
    const active = items.filter(isActive).length;
    const expiring = items.filter((item) => isActive(item) && item.current_period_end && (new Date(String(item.current_period_end).replace(' ', 'T')).getTime() - Date.now()) < 7 * 86400000).length;
    const revoked = items.filter((item) => item.status === 'revoked').length;
    root.innerHTML = `<div class="stats-grid"><div class="stat-card"><iconify-icon icon="lucide:key-round"></iconify-icon><div class="stat-label">Total licenses</div><h2 class="stat-value">${items.length}</h2></div><div class="stat-card"><iconify-icon icon="lucide:badge-check"></iconify-icon><div class="stat-label">Active licenses</div><h2 class="stat-value">${active}</h2></div><div class="stat-card"><iconify-icon icon="lucide:clock-3"></iconify-icon><div class="stat-label">Expiring soon</div><h2 class="stat-value">${expiring}</h2></div><div class="stat-card"><iconify-icon icon="lucide:ban"></iconify-icon><div class="stat-label">Revoked</div><h2 class="stat-value">${revoked}</h2></div></div><section class="panel"><div class="panel-header"><div><h2>Recent licenses</h2><p>Latest license records from Turso.</p></div><a class="button button-ghost button-small" href="/dashboard/licenses">View all <iconify-icon icon="lucide:arrow-up-right" width="15"></iconify-icon></a></div>${licenseTable(items.slice(0, 8), false)}</section>`;
    bindCopy();
  } catch (error) { root.innerHTML = `<div class="panel">${empty('lucide:cloud-off', `Could not load licenses: ${esc(apiError(error))}`)}</div>`; }
}

async function renderLicenses() {
  setPage('Licenses', 'Search, inspect, and control access.'); loading();
  try { await loadLicenses(); root.innerHTML = `<section class="panel"><div class="panel-header"><div><h2>All licenses</h2><p>Maximum 100 latest licenses are loaded from the API.</p></div><div class="panel-actions"><div class="search-box"><iconify-icon icon="lucide:search" width="16"></iconify-icon><input id="license-search" placeholder="Search email, key, plan..." /></div><button class="button button-ghost button-small" id="export-licenses"><iconify-icon icon="lucide:download" width="15"></iconify-icon>CSV</button><button class="button button-small" id="new-license"><iconify-icon icon="lucide:plus" width="15"></iconify-icon>Add license</button></div></div><div id="license-table">${licenseTable(licenses)}</div></section>`; bindLicenseEvents(); document.querySelector('#new-license')?.addEventListener('click', () => openLicense()); } catch (error) { root.innerHTML = `<div class="panel">${empty('lucide:cloud-off', esc(apiError(error)))}</div>`; }
}

const licenseForm = () => `<div class="modal-header"><h2>New license</h2><button class="icon-button" data-modal-close type="button"><iconify-icon icon="lucide:x"></iconify-icon></button></div><form id="license-form"><div class="modal-body"><div class="field"><label>Email</label><input name="email" type="email" placeholder="customer@example.com" required /></div><div class="field"><label>License key <span class="helper">(kosongkan untuk generate otomatis)</span></label><input name="key" placeholder="AUTO-XXXX-XXXX-XXXX" pattern="[A-Za-z0-9-]{8,64}" /></div><div class="form-grid"><div class="field"><label>Duration (days)</label><input name="duration_days" type="number" min="1" max="3650" value="30" required /></div><div class="field"><label>Max devices</label><input name="max_devices" type="number" min="1" max="100" value="1" required /></div><div class="field"><label>Plan type</label><input name="plan_type" placeholder="Contoh: Premium VIP" maxlength="50" value="Monthly" required /></div></div><div class="message" id="modal-error"></div></div><div class="modal-footer"><button class="button button-ghost" data-modal-close type="button">Cancel</button><button class="button" type="submit">Create license</button></div></form>`;
function openLicense() { openModal(licenseForm()); modal.querySelector('[data-modal-close]')?.addEventListener('click', closeModal); modal.querySelector('#license-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget as HTMLFormElement)); const body = { email: values.email, key: values.key || undefined, duration_days: Number(values.duration_days), max_devices: Number(values.max_devices), plan_type: values.plan_type }; try { const data = await api<{ license: AnyRecord }>('/admin/licenses', json('POST', body)); closeModal(); showToast(`License created: ${data.license?.key || 'success'}`); await renderLicenses(); } catch (error) { const message = modal.querySelector('#modal-error') as HTMLElement; message.className = 'message error is-visible'; message.textContent = apiError(error); } }); }

function bindLicenseEvents() {
  const table = document.querySelector('#license-table')!;
  const draw = (items: AnyRecord[]) => { table.innerHTML = licenseTable(items); bindCopy(); bindLicenseActions(); };
  document.querySelector('#license-search')?.addEventListener('input', (event) => { const q = (event.target as HTMLInputElement).value.toLowerCase(); draw(licenses.filter((item) => [item.email, item.key, item.plan_type, item.status].some((value) => String(value).toLowerCase().includes(q)))); });
  document.querySelector('#export-licenses')?.addEventListener('click', () => downloadCsv('licenses.csv', licenses));
  bindCopy(); bindLicenseActions();
}
function bindLicenseActions() {
  document.querySelectorAll<HTMLElement>('[data-edit-license]').forEach((button) => button.addEventListener('click', () => openEditLicense(licenses.find((item) => item.id === Number(button.dataset.editLicense)))));
  document.querySelectorAll<HTMLElement>('[data-revoke]').forEach((button) => button.addEventListener('click', async () => { if (!confirm('Revoke license ini?')) return; try { await api(`/admin/licenses/${button.dataset.revoke}/revoke`, { method: 'POST' }); showToast('License revoked.'); await renderLicenses(); } catch (error) { showError(error); } }));
  document.querySelectorAll<HTMLElement>('[data-reactivate]').forEach((button) => button.addEventListener('click', async () => { try { await api(`/admin/licenses/${button.dataset.reactivate}/reactivate`, { method: 'POST' }); showToast('License reactivated.'); await renderLicenses(); } catch (error) { showError(error); } }));
  document.querySelectorAll<HTMLElement>('[data-activations]').forEach((button) => button.addEventListener('click', () => showActivations(Number(button.dataset.activations))));
}
const editLicenseForm = (item: AnyRecord) => `<div class="modal-header"><div><h2>Edit license</h2><p class="helper mono">${esc(item.key)}</p></div><button class="icon-button" data-modal-close type="button"><iconify-icon icon="lucide:x"></iconify-icon></button></div><form id="edit-license-form"><div class="modal-body"><div class="field"><label>Email</label><input name="email" type="email" value="${esc(item.email)}" required /></div><div class="form-grid"><div class="field"><label>Plan type</label><input name="plan_type" value="${esc(item.plan_type)}" maxlength="50" required /></div><div class="field"><label>Expires at</label><input name="expires_at" type="date" value="${dateInput(item.current_period_end)}" required /></div><div class="field"><label>Max devices</label><input name="max_devices" type="number" min="1" max="100" value="${esc(item.max_devices)}" required /></div></div><p class="helper">License key tidak diubah agar aplikasi client tetap terhubung. Jika license sedang revoked, status tetap revoked.</p><div class="message" id="modal-error"></div></div><div class="modal-footer"><button class="button button-ghost" data-modal-close type="button">Cancel</button><button class="button" type="submit">Save changes</button></div></form>`;
function openEditLicense(item?: AnyRecord) { if (!item) return; openModal(editLicenseForm(item)); modal.querySelector('[data-modal-close]')?.addEventListener('click', closeModal); modal.querySelector('#edit-license-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget as HTMLFormElement)); const body = { email: values.email, plan_type: values.plan_type, expires_at: values.expires_at, max_devices: Number(values.max_devices) }; try { await api(`/admin/licenses/${item.id}`, json('PUT', body)); closeModal(); showToast('License updated.'); await renderLicenses(); } catch (error) { const message = modal.querySelector('#modal-error') as HTMLElement; message.className = 'message error is-visible'; message.textContent = apiError(error); } }); }
async function showActivations(id: number) {
  openModal('<div class="modal-header"><h2>Device activations</h2><button class="icon-button" data-modal-close type="button"><iconify-icon icon="lucide:x"></iconify-icon></button></div><div class="modal-body"><div class="loading"><span class="spinner"></span>Loading...</div></div>');
  try { const data = await api<{ license: AnyRecord; activations: AnyRecord[] }>(`/admin/licenses/${id}/activations`); const list = data.activations.length ? `<div class="activation-list">${data.activations.map((item) => `<div class="activation-item"><div><strong>${esc(item.device_name || 'Unnamed device')}</strong><span>${esc(item.platform)} · last seen ${date(item.last_seen)}</span><code class="mono">${esc(item.device_hash)}</code></div><button class="row-action" data-unbind="${item.id}" title="Unbind device"><iconify-icon icon="lucide:unlink" width="16"></iconify-icon></button></div>`).join('')}</div>` : empty('lucide:cpu', 'Belum ada device activation.'); modal.innerHTML = `<div class="modal-header"><div><h2>Device activations</h2><p class="helper">${esc(data.license.key)} · ${data.activations.length}/${esc(data.license.max_devices)} devices</p></div><button class="icon-button" data-modal-close type="button"><iconify-icon icon="lucide:x"></iconify-icon></button></div><div class="modal-body">${list}</div>`; modal.querySelector('[data-modal-close]')?.addEventListener('click', closeModal); modal.querySelectorAll<HTMLElement>('[data-unbind]').forEach((button) => button.addEventListener('click', async () => { if (!confirm('Lepaskan device ini?')) return; try { await api(`/admin/licenses/${id}/activations/${button.dataset.unbind}`, { method: 'DELETE' }); showToast('Device unbound.'); await showActivations(id); } catch (error) { showError(error); } })); } catch (error) { modal.querySelector('.modal-body')!.innerHTML = `<div class="message error is-visible">${esc(apiError(error))}</div>`; }
}

const mappingForm = (item?: AnyRecord) => `<div class="modal-header"><h2>${item ? 'Edit mapping' : 'New mapping'}</h2><button class="icon-button" data-modal-close type="button"><iconify-icon icon="lucide:x"></iconify-icon></button></div><form id="mapping-form"><div class="modal-body"><div class="field"><label>Title pattern</label><input name="title_pattern" value="${esc(item?.title_pattern || '')}" required /></div><div class="form-grid"><div class="field"><label>Duration (days)</label><input name="duration_days" type="number" min="1" value="${esc(item?.duration_days || 30)}" required /></div><div class="field"><label>Max devices</label><input name="max_devices" type="number" min="1" max="100" value="${esc(item?.max_devices || 1)}" required /></div><div class="field"><label>Plan type</label><input name="plan_type" value="${esc(item?.plan_type || '')}" placeholder="Contoh: Premium VIP" maxlength="50" required /></div><label class="toggle"><input name="is_active" type="checkbox" ${item?.is_active === 0 ? '' : 'checked'} /> Active</label></div><div class="message" id="modal-error"></div></div><div class="modal-footer"><button class="button button-ghost" data-modal-close type="button">Cancel</button><button class="button" type="submit">Save mapping</button></div></form>`;
async function renderMappings() { setPage('Product mappings', 'Turn product titles into predictable plans.'); loading(); try { const data = await api<{ mappings: AnyRecord[] }>('/admin/mapping'); mappings = data.mappings || []; root.innerHTML = `<section class="panel"><div class="panel-header"><div><h2>Product mappings</h2><p>Rules used when creating licenses from Lynk transactions.</p></div><div class="panel-actions"><button class="button button-ghost button-small" id="export-mappings"><iconify-icon icon="lucide:download" width="15"></iconify-icon>CSV</button><button class="button button-small" id="new-mapping"><iconify-icon icon="lucide:plus" width="15"></iconify-icon>Add mapping</button></div></div>${mappings.length ? `<div class="table-wrap"><table><thead><tr><th>Title pattern</th><th>Plan</th><th>Duration</th><th>Devices</th><th>Status</th><th>Actions</th></tr></thead><tbody>${mappings.map((item) => `<tr><td><strong>${esc(item.title_pattern)}</strong></td><td>${esc(item.plan_type)}</td><td>${esc(item.duration_days)} days</td><td>${esc(item.max_devices)}</td><td>${item.is_active ? statusBadge('active', 'active') : statusBadge('inactive', 'inactive')}</td><td><div class="row-actions"><button class="row-action" data-edit-mapping="${item.id}" title="Edit"><iconify-icon icon="lucide:pencil" width="15"></iconify-icon></button><button class="row-action" data-delete-mapping="${item.id}" title="Delete"><iconify-icon icon="lucide:trash-2" width="15"></iconify-icon></button></div></td></tr>`).join('')}</tbody></table></div>` : empty('lucide:blocks', 'Belum ada product mapping.')}</section>`; document.querySelector('#new-mapping')?.addEventListener('click', () => openMapping()); document.querySelector('#export-mappings')?.addEventListener('click', () => downloadCsv('product-mappings.csv', mappings)); document.querySelectorAll<HTMLElement>('[data-edit-mapping]').forEach((button) => button.addEventListener('click', () => openMapping(mappings.find((item) => item.id === Number(button.dataset.editMapping))))); document.querySelectorAll<HTMLElement>('[data-delete-mapping]').forEach((button) => button.addEventListener('click', () => deleteMapping(Number(button.dataset.deleteMapping)))); } catch (error) { root.innerHTML = `<div class="panel">${empty('lucide:cloud-off', esc(apiError(error)))}</div>`; } }
function openMapping(item?: AnyRecord) { openModal(mappingForm(item)); modal.querySelector('[data-modal-close]')?.addEventListener('click', closeModal); modal.querySelector('#mapping-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget as HTMLFormElement; const values = Object.fromEntries(new FormData(form)); const body = { title_pattern: values.title_pattern, duration_days: Number(values.duration_days), plan_type: values.plan_type, max_devices: Number(values.max_devices), is_active: values.is_active === 'on' }; try { await api(item ? `/admin/mapping/${item.id}` : '/admin/mapping', json(item ? 'PUT' : 'POST', body)); closeModal(); showToast('Mapping saved.'); await renderMappings(); } catch (error) { const message = modal.querySelector('#modal-error') as HTMLElement; message.className = 'message error is-visible'; message.textContent = apiError(error); } }); }
async function deleteMapping(id: number) { if (!confirm('Hapus mapping ini?')) return; try { await api(`/admin/mapping/${id}`, { method: 'DELETE' }); showToast('Mapping deleted.'); await renderMappings(); } catch (error) { showError(error); } }

const accountForm = (item?: AnyRecord) => `<div class="modal-header"><h2>${item ? 'Edit Lynk account' : 'New Lynk account'}</h2><button class="icon-button" data-modal-close type="button"><iconify-icon icon="lucide:x"></iconify-icon></button></div><form id="account-form"><div class="modal-body"><div class="form-grid"><div class="field"><label>Account name</label><input name="name" value="${esc(item?.name || '')}" required /></div><div class="field"><label>Slug</label><input name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value="${esc(item?.slug || '')}" required /></div><div class="field full"><label>Merchant key ${item ? '(leave empty to keep current)' : ''}</label><input name="merchant_key" type="password" ${item ? '' : 'required'} autocomplete="new-password" /></div><label class="toggle"><input name="is_active" type="checkbox" ${item?.is_active === 0 ? '' : 'checked'} /> Active</label></div><div class="message" id="modal-error"></div></div><div class="modal-footer"><button class="button button-ghost" data-modal-close type="button">Cancel</button><button class="button" type="submit">Save account</button></div></form>`;
async function renderAccounts() { setPage('Lynk accounts', 'Manage webhook destinations securely.'); loading(); try { const data = await api<{ accounts: AnyRecord[] }>('/admin/lynk-accounts'); accounts = data.accounts || []; const webhookBase = (import.meta.env.PUBLIC_API_URL || '').replace(/\/$/, ''); root.innerHTML = `<section class="panel"><div class="panel-header"><div><h2>Lynk accounts</h2><p>Merchant keys stay encrypted and are never returned by the API.</p></div><div class="panel-actions"><button class="button button-small" id="new-account"><iconify-icon icon="lucide:plus" width="15"></iconify-icon>Add account</button></div></div>${accounts.length ? `<div class="table-wrap"><table><thead><tr><th>Account</th><th>Slug</th><th>Webhook URL</th><th>Status</th><th>Actions</th></tr></thead><tbody>${accounts.map((item) => { const url = `${webhookBase}${item.webhook_path}`; return `<tr><td><strong>${esc(item.name)}</strong></td><td class="mono">${esc(item.slug)}</td><td><span class="mono">${esc(url)}</span><button class="copy-button" data-copy="${esc(url)}" title="Copy webhook URL"><iconify-icon icon="lucide:copy" width="14"></iconify-icon></button></td><td>${item.is_active ? statusBadge('active', 'active') : statusBadge('inactive', 'inactive')}</td><td><div class="row-actions"><button class="row-action" data-edit-account="${item.id}" title="Edit"><iconify-icon icon="lucide:pencil" width="15"></iconify-icon></button><button class="row-action" data-delete-account="${item.id}" title="Delete"><iconify-icon icon="lucide:trash-2" width="15"></iconify-icon></button></div></td></tr>`; }).join('')}</tbody></table></div>` : empty('lucide:store', 'Belum ada Lynk account.')}</section>`; bindCopy(); document.querySelector('#new-account')?.addEventListener('click', () => openAccount()); document.querySelectorAll<HTMLElement>('[data-edit-account]').forEach((button) => button.addEventListener('click', () => openAccount(accounts.find((item) => item.id === Number(button.dataset.editAccount))))); document.querySelectorAll<HTMLElement>('[data-delete-account]').forEach((button) => button.addEventListener('click', () => deleteAccount(Number(button.dataset.deleteAccount)))); } catch (error) { root.innerHTML = `<div class="panel">${empty('lucide:cloud-off', esc(apiError(error)))}</div>`; } }
function openAccount(item?: AnyRecord) { openModal(accountForm(item)); modal.querySelector('[data-modal-close]')?.addEventListener('click', closeModal); modal.querySelector('#account-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget as HTMLFormElement)); const body: AnyRecord = { name: values.name, slug: values.slug, is_active: values.is_active === 'on' }; if (values.merchant_key) body.merchant_key = values.merchant_key; try { await api(item ? `/admin/lynk-accounts/${item.id}` : '/admin/lynk-accounts', json(item ? 'PUT' : 'POST', body)); closeModal(); showToast('Lynk account saved.'); await renderAccounts(); } catch (error) { const message = modal.querySelector('#modal-error') as HTMLElement; message.className = 'message error is-visible'; message.textContent = apiError(error); } }); }
async function deleteAccount(id: number) { if (!confirm('Hapus account ini? Jika sudah punya history, nonaktifkan saja.')) return; try { await api(`/admin/lynk-accounts/${id}`, { method: 'DELETE' }); showToast('Account deleted.'); await renderAccounts(); } catch (error) { showError(error); } }

async function renderLogs() { setPage('Audit logs', 'Track changes across the admin workspace.'); loading(); try { const data = await api<{ logs: AnyRecord[] }>('/admin/audit-logs'); logs = data.logs || []; root.innerHTML = `<section class="panel"><div class="panel-header"><div><h2>Audit activity</h2><p>Latest 200 admin and device events.</p></div><div class="panel-actions"><div class="search-box"><iconify-icon icon="lucide:search" width="16"></iconify-icon><input id="log-search" placeholder="Search action or target..." /></div><button class="button button-ghost button-small" id="export-logs"><iconify-icon icon="lucide:download" width="15"></iconify-icon>CSV</button></div></div><div id="logs-table">${logsTable(logs)}</div></section>`; bindLogEvents(); } catch (error) { root.innerHTML = `<div class="panel">${empty('lucide:cloud-off', esc(apiError(error)))}</div>`; } }
function logsTable(items: AnyRecord[]) { if (!items.length) return empty('lucide:scroll-text', 'Belum ada audit log.'); return `<div class="table-wrap"><table><thead><tr><th>Action</th><th>Target</th><th>License</th><th>Details</th><th>Created</th></tr></thead><tbody>${items.map((item) => `<tr><td><strong>${esc(item.action)}</strong></td><td>${esc(item.target_type)} #${esc(item.target_id)}</td><td>${esc(item.license_id)}</td><td class="mono">${esc(item.details)}</td><td>${date(item.created_at)}</td></tr>`).join('')}</tbody></table></div>`; }
function bindLogEvents() { document.querySelector('#log-search')?.addEventListener('input', (event) => { const q = (event.target as HTMLInputElement).value.toLowerCase(); document.querySelector('#logs-table')!.innerHTML = logsTable(logs.filter((item) => JSON.stringify(item).toLowerCase().includes(q))); }); document.querySelector('#export-logs')?.addEventListener('click', () => downloadCsv('audit-logs.csv', logs)); }

function downloadCsv(filename: string, rows: AnyRecord[]) { if (!rows.length) return showToast('Tidak ada data untuk diexport.'); const headers = [...new Set(rows.flatMap((row) => Object.keys(row)))]; const csv = [headers, ...rows.map((row) => headers.map((header) => String(row[header] ?? '').replace(/"/g, '""')))].map((row) => row.map((value) => `"${value}"`).join(',')).join('\n'); const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = filename; link.click(); URL.revokeObjectURL(link.href); }

async function boot() { requireSession(); const username = sessionStorage.getItem('lm-admin-user') || 'Admin'; document.querySelector('#profile-name')!.textContent = username; document.querySelector('#profile-avatar')!.textContent = username.slice(0, 1).toUpperCase(); document.querySelector('#logout-button')?.addEventListener('click', () => { clearSession(); window.location.href = '/login'; }); const path = location.pathname.replace(/\/+$/, '') || '/'; if (path === '/dashboard/mappings') await renderMappings(); else if (path === '/dashboard/lynk-accounts') await renderAccounts(); else if (path === '/dashboard/audit-logs') await renderLogs(); else if (path === '/dashboard/licenses') await renderLicenses(); else await renderOverview(); }
boot();
